### ISSUE TITLE
play-navigator_2.10

### ISSUE THREAD

**Issue by jamesward** [teamon/play-navigator#9]
Right now the `play-navigator` package is built with a Scala version of `2.10.0` which means the package is `play-navigator_2.10.0` but I believe the right way now is to build against the major version, not the minor version, so the package should be `play-navigator_2.10` instead.  I'm not totally sure how to do that in your build but projects like Akka and Play are now doing it that way so it must be possible.  :)

**Comment by onsails** [comment]
+1 to the issue. Following README leads to sbt update errors when using Scala 2.10

**Comment by teamon** [comment]
After quick check it seams that this will not be so easy. In build.properties there is `sbt.version=0.11.3` which does not support `scalaBinaryVersion`. Upgrading to sbt 12.x is not so easy because there is no sbt-scalajars for 12.x, and updating sbt-scalajars is even more pain since it is now very outdated. I'm planning to move away from scalajars.org because the project is unfortunately dead - I have no time to maintain it. Can you point me to some other simple solution for publishing artifacts? I've tried sonatype back in the day and it was quite painful to set up.

(If anyone would like to do some work on scalajars.org please let me know)

**Comment by onsails** [comment]
@teamon there is very simple solution for publishing artifacts: [Apache Archiva](http://archiva.apache.org). It just does its work.

**Comment by teamon** [comment]
I was actually thinking about moving away from self-hosted solution.

**Comment by jamesward** [comment]
I know a bunch of people use GitHub Pages for hosting repos.  I think it's pretty easy to setup.  Or you can use the Maven OSS repo which also isn't too hard to setup.

**Comment by teamon** [comment]
I've changed source to repo.teamon.eu and published for 2.10. Please check if everything is ok now.

**Comment by jamesward** [comment]
Works great!  Thank you!
